allowBuilds:
  esbuild: true
  sharp: true
autoInstallPeers: false
onlyBuiltDependencies:
  - esbuild
  - sharp
peerDependencyRules:
  allowedVersions:
    tailwindcss: ">=4.0.0"
  ignoreMissing:
    - "@astrojs/starlight"
