// Holy shit this file generated by LLM

import type { CollectionEntry } from "astro:content";

const MORE_MARKER_REGEX = /<!--\s*more\s*-->/i;
const HTML_COMMENT_REGEX = /<!--[\s\S]*?-->/g;
const FRONTMATTER_REGEX = /^---\s*\n[\s\S]*?\n---\s*/;
const FENCED_CODE_BLOCK_REGEX = /```[\s\S]*?```/g;
const INLINE_CODE_REGEX = /`([^`]+)`/g;
const IMAGE_REGEX = /!\[([^\]]*)\]\([^)]+\)/g;
const LINK_REGEX = /\[([^\]]+)\]\([^)]+\)/g;
const HEADING_REGEX = /^\s{0,3}#{1,6}\s+/gm;
const BLOCKQUOTE_REGEX = /^\s{0,3}>\s?/gm;
const LIST_MARKER_REGEX = /^\s{0,3}(?:[-*+]|\d+\.)\s+/gm;
const EMPHASIS_REGEX = /[*_~]/g;
const WHITESPACE_REGEX = /\s+/g;

const EXPLICIT_SUMMARY_LENGTH = 320;
const AUTO_EXCERPT_LENGTH = 200;

function truncateText(text: string, maxLength: number): string {
    if (text.length <= maxLength) {
        return text;
    }

    const truncated = text.slice(0, maxLength).trimEnd();
    const lastSpace = truncated.lastIndexOf(" ");
    const safeText = lastSpace > maxLength * 0.6
        ? truncated.slice(0, lastSpace)
        : truncated;

    return `${safeText}...`;
}

function toPlainText(markdown: string): string {
    return markdown
        .replace(FRONTMATTER_REGEX, "")
        .replace(HTML_COMMENT_REGEX, " ")
        .replace(FENCED_CODE_BLOCK_REGEX, " ")
        .replace(IMAGE_REGEX, "$1")
        .replace(LINK_REGEX, "$1")
        .replace(INLINE_CODE_REGEX, "$1")
        .replace(HEADING_REGEX, "")
        .replace(BLOCKQUOTE_REGEX, "")
        .replace(LIST_MARKER_REGEX, "")
        .replace(EMPHASIS_REGEX, "")
        .replace(WHITESPACE_REGEX, " ")
        .trim();
}

export function getPostSummary(post: CollectionEntry<"posts">): string | undefined {
    const body = post.body?.trim();

    if (!body) {
        return undefined;
    }

    const moreMatch = body.match(MORE_MARKER_REGEX);
    const summarySource = moreMatch
        ? body.slice(0, moreMatch.index)
        : body;
    const plainText = toPlainText(summarySource);

    if (!plainText) {
        return undefined;
    }

    return truncateText(
        plainText,
        moreMatch ? EXPLICIT_SUMMARY_LENGTH : AUTO_EXCERPT_LENGTH,
    );
}
